---
language: java
dist: xenial

jdk:
  - openjdk8

notifications:
  email: true

# After creating your SDK project from this template repository,
# set BINTRAY_REPO to the name of your project's bintray repository.
# See https://github.com/IBM/ibm-cloud-sdk-common/blob/master/JavaDeploy.md for details.
env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"
    - BINTRAY_ORG=ibm-cloud-sdks
    - BINTRAY_REPO=my-services-java-sdk

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"


before_install:
- sudo apt-get update
- sudo apt-get install python
- nvm install 12
- npm install -g npm@6.x
- echo -e "machine github.ibm.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
# Uncomment this section and update as needed to decrypt each configuration file.
# - >-
#       [ -z "${TRAVIS_TAG}" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]
#       && openssl aes-256-cbc -K $my_key  -iv $my_iv -in myservice.env.enc -out myservice.env -d
#       || true

install:
- curl -s https://codecov.io/bash > $HOME/codecov-bash.sh && chmod +x $HOME/codecov-bash.sh

before_script:
- echo "TRAVIS_TAG = '${TRAVIS_TAG}'"
- >-
      [ -n "${TRAVIS_TAG}" ]
      && mvn versions:set -DnewVersion=${TRAVIS_TAG} -DgenerateBackupPoms=false
      || true

script:
-  mvn clean verify $MVN_ARGS

# To enable semantic-release, uncomment these sections.
# before_deploy:
# - pip install --user bump2version
# - npm install @semantic-release/changelog
# - npm install @semantic-release/exec
# - npm install @semantic-release/git
# - npm install @semantic-release/github
#
# deploy:
#   # On master, run semrel to create a new tagged-release.
#   - provider: script
#     script: npx semantic-release
#     skip_cleanup: true
#     on:
#       branch: master
#   # Publish jars on bintray for a tagged release.
#   - provider: script
#     script:
#     - >-
#           mvn deploy $MVN_ARGS -DskipTests
#           && build/bintraySync.sh $BINTRAY_USER $BINTRAY_APIKEY $BINTRAY_ORG $BINTRAY_REPO $TRAVIS_TAG
#     skip_cleanup: true
#     on:
#       tags: true
#       jdk: openjdk8
#   # Publish javadocs to gh-pages only for a tagged-release.
#   - provider: script
#     script: "./build/publish-javadoc.sh"
#     skip_cleanup: true
#     on:
#       tags: true
#       jdk: openjdk8
#   # Upload code coverage reports to codecov.io for master or tagged release
#   - provider: script
#     script: $HOME/codecov-bash.sh -s modules/coverage-reports/target/site/jacoco-aggregate -t $CODECOV_TOKEN
#     skip_cleanup: true
#     on:
#       condition: $TRAVIS_BRANCH == master || -n "$TRAVIS_TAG"
#       jdk: openjdk8
