/*
 * (C) Copyright IBM Corp. 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package com.ibm.cloud.secrets_manager_sdk.secrets_manager.v2.model;

import com.ibm.cloud.sdk.core.service.model.GenericModel;

/**
 * The service-specific custom role. CRN is accepted. The role is assigned as part of an access policy to any
 * auto-generated IAM service ID.  If you provide an existing service ID, it is added to the access policy for that ID.
 * If a role is not provided, any new service IDs that are autogenerated, will not have an assigned access policy and
 * provided service IDs are not changed in any way.  Refer to the service documentation for supported roles.
 */
public class ServiceCredentialsSourceServiceRole extends GenericModel {

  protected String crn;

  /**
   * Builder.
   */
  public static class Builder {
    private String crn;

    /**
     * Instantiates a new Builder from an existing ServiceCredentialsSourceServiceRole instance.
     *
     * @param serviceCredentialsSourceServiceRole the instance to initialize the Builder with
     */
    private Builder(ServiceCredentialsSourceServiceRole serviceCredentialsSourceServiceRole) {
      this.crn = serviceCredentialsSourceServiceRole.crn;
    }

    /**
     * Instantiates a new builder.
     */
    public Builder() {
    }

    /**
     * Instantiates a new builder with required properties.
     *
     * @param crn the crn
     */
    public Builder(String crn) {
      this.crn = crn;
    }

    /**
     * Builds a ServiceCredentialsSourceServiceRole.
     *
     * @return the new ServiceCredentialsSourceServiceRole instance
     */
    public ServiceCredentialsSourceServiceRole build() {
      return new ServiceCredentialsSourceServiceRole(this);
    }

    /**
     * Set the crn.
     *
     * @param crn the crn
     * @return the ServiceCredentialsSourceServiceRole builder
     */
    public Builder crn(String crn) {
      this.crn = crn;
      return this;
    }
  }

  protected ServiceCredentialsSourceServiceRole() { }

  protected ServiceCredentialsSourceServiceRole(Builder builder) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(builder.crn,
      "crn cannot be null");
    crn = builder.crn;
  }

  /**
   * New builder.
   *
   * @return a ServiceCredentialsSourceServiceRole builder
   */
  public Builder newBuilder() {
    return new Builder(this);
  }

  /**
   * Gets the crn.
   *
   * The service role CRN.
   *
   * @return the crn
   */
  public String crn() {
    return crn;
  }
}

